do not rely on version from Manifest
pf4j/pf4j pull request #455
Opened 2021-06-13 16:21 UTC by wolframhaussig

solves #390

- added generated class Pf4jVersion to contain the current version
- added templating-maven-plugin to add project version into Pf4jVersion
- added UnitTest for version

2021-06-13 18:37 UTC, decebals commented
It looks good. I prefer to rename `Pf4jVersion` to avoid duplication in `Pf4jVersion.VERSION` and to be able to put other useful information in the future (let's say `BUILD_NUMBER` as an example).
@wolframhaussig what do you think?

2021-06-13 18:38 UTC, decebals requested changes

2021-06-13 18:38 UTC, decebals commented on pf4j/src/test/java/org/pf4j/AbstractPluginManagerTest.java
> +    @Test
please, add an empty line between methods

2021-06-14 04:26 UTC, wolframhaussig commented
@decebals You are right. Should I rename the class `Pf4jVersion` to `Pf4jInfo`?

2021-06-14 19:59 UTC, decebals commented
> @decebals You are right. Should I rename the class `Pf4jVersion` to `Pf4jInfo`?

I think that `Pf4jInfo` is a better name.

2021-06-14 20:02 UTC, decebals commented on pf4j/src/main/java-templates/org/pf4j/Pf4jVersion.java
> + * class provides access to the current Pf4j version which might otherwise not be possible(e.g. in Uber-Jars where the Manifest wass overridden)
I prefer to start with upper case the sentence. I try not to be annoying :smile:.

2021-06-15 03:29 UTC, wolframhaussig commented
@decebals I renamed the class and fixed the javadoc so feel free to have a look.

2021-06-15 16:57 UTC, merged