#499
pf4j/pf4j pull request #586
Opened 2024-06-25 21:33 UTC by etojesaandro

Always look for the EXTENSIONS_RESOURCE in PluginClassLoader first (PDA strategy)

2024-06-26 19:30 UTC, decebals commented
@etojesaandro 
It would be nice if you could add a test to this PR.
We have [PluginClassLoaderTest](https://github.com/pf4j/pf4j/blob/master/pf4j/src/test/java/org/pf4j/PluginClassLoaderTest.java).

2024-06-28 07:51 UTC, etojesaandro commented
> @etojesaandro It would be nice if you could add a test to this PR. We have [PluginClassLoaderTest](https://github.com/pf4j/pf4j/blob/master/pf4j/src/test/java/org/pf4j/PluginClassLoaderTest.java).

The set of tests were implemented

2024-06-28 14:05 UTC, decebals requested changes
It looks good for me. Only some minor requests.

2024-06-28 14:05 UTC, decebals commented on pf4j/src/test/java/org/pf4j/PluginClassLoaderTest.java
> +
Remove this empty line

2024-06-28 14:05 UTC, decebals commented on pf4j/src/test/java/org/pf4j/PluginClassLoaderTest.java
> +            .build();
Preserve indentation

2024-06-29 19:30 UTC, merged

2024-06-29 19:30 UTC, decebals commented
@etojesaandro Thanks for your contribution!